prompt_6 = """
Les données, représentent un verbatim d'un client après une visite de son espace client sur notre site d'assurance.

Tu es un classifieur et tu dois classifier ce verbatim parmi les classes ci-dessous, Tu dois exlusivement utiliser ces classes rien d'autre.


DEBUT CLASSES

- Autre

- Verbatim_Indechiffrable

FIN CLASSES

Tu suis les règles suivantes:

DEBUT REGLES

- La réponse doit être la classe les plus proche et importante pour détecté le problème du client depuis le verbatim.
- N'introduis pas de nouvelles classes.
- Ne reformule pas les classes existantes.
- Un verbatim peut être classifié que dans une classe.
- Utilise la classe 'Autre' lorsque le verbatim ne peut pas être classifié dans les classes données
- Pas de commentaire, seulement la réponse
- l'output doit être seulement la classe détéctée.


FIN REGLES


DEBUT RAISONNEMENT

- Identifie les caractéristiques les plus importantes dans le verbatim.
- Détermine si ce n’est pas un verbatim  illisible, incompréhensible auquel cas tu l’affecte à la classe "Verbatim_Indechiffrable"
- Autrement affecte le verbatim à la classe "Autre" s'il est compréhensible


FIN RAISONNEMENT

DEBUT EXPLICATION

-  "Verbatim_Indechiffrable" : représente un commentaire qui ne contient pas de texte intelligible ou structuré, semblable à une chaîne de caractères aléatoires ou du bruit textuel. Cette classe  est utilisée pour filtrer des entrées qui ne constituent pas un commentaire valable ou compréhensible par les humains. Elle pourrait également servir à détecter et gérer des erreurs dans la saisie des données

- "Autre"  : Cette classe doit être utilisée lorsque l’internaute dépose un Verbatim lisible et compréhensible par l'humain.


FIN EXPLICATION

DEBUT EXEMPLES




Input  : M	| Output :  "Verbatim_Indechiffrable"
Input  : yvetteperriat@gmail.com| Output :  "Verbatim_Indechiffrable"
Input  : N'eo ket sklaer ma 'ha en-dro pe get ?| Output :  "Verbatim_Indechiffrable"
Input  : jddk  | Output : "Verbatim_Indechiffrable"

Input  : accès bloqué pour obtenir une attestation d'assurance.  | Output :  "Autre"
Input  : Impossible de télécharger une attestation pour location de salle  | Output :  "Autre"
Input  : difficile de trouver les attestation en PDF  | Output :  "Autre"
Input  : Je n'ai pas eu le document d'attestation demandé de mon véhicule 133 BMD 974. Très déçue.  | Output :  "Autre"
Input  : Je trouve dommage de ne pas pouvoir télécharger directement une attestation de RC  | Output :  "Autre"
Input  : Difficile de retrouver l'attestation scolaire : le parcours n'est pas intuitif. Il faudrait un dossier dédié aux attestataions dans les documents.  | Output :  "Autre"
Input  : Nécessité de contacter un conseiller dès que l'on demande une attestation pourant basique (ex : attestation RC au nom de ma femme ou ma fille)  | Output :  "Autre"
Input  : Je voulais une attestation d'assurance pour mes voitures. C'est impossible. Que se soit dans la rubrique 'attestation d'assurance auto' ou dans 'document's, on obtient que des pages blanches et ce, à plusieurs heures de la journée.  J'appellerai demain, s'il y a quelqu'un au bureau !  | Output :  "Autre"
Input  : impossible de récuperer une attestation d'assurance  | Output :  "Autre"
Input  : impossible de visualiser les clauses de la mutuelle sante  | Output :  "Autre"
Input  : Je ne peux rien consulter relatif a mes contrat.   | Output :  "Autre"
Input  : Pas accès aux conditions générales ni particulières de mon contrat  | Output :  "Autre"
Input  : Il serait bien de voir le détail du contrat (remboursement part mutuelle) on ne sait pas réellement à quoi on peut prétendre !  | Output :  "Autre"
Input  : Difficile de trouver des infos sur son contrat 'Conduire'  | Output :  "Autre"
Input  : je suis nouveau client et je n'ai pas réussi à consulter les garanties de mon contrat santé.  | Output :  "Autre"
Input  : je voudrais avoir le détail de mon contrat santé  | Output :  "Autre"
Input  : je ne trouve pas mon contrat d'assurance-vie  | Output :  "Autre"
Input  : Je ne trouve pas mes contrats.  | Output :  "Autre"
Input  : impossible derecuperer mes documents sur mon espace personnel aujourd hui 3/12  | Output :  "Autre"
Input  : Il manque souvent des documents  | Output :  "Autre"
Input  : Toujours impossible de voir les documents. Rien n'évolue.  | Output :  "Autre"
Input  : pas toujours évident de trouver des documents  | Output :  "Autre"
Input  : La recherche de document est assez compliqué pour trouver le bon document  | Output :  "Autre"
Input  : assez difficile de trouver les documents  | Output :  "Autre"
Input  : quelques difficultés à trouver certains documents  | Output :  "Autre"
Input  : J ai un peu tourné en rond pour accéder au document  | Output :  "Autre"
Input  : site très mal fait, difficultés à trouver un document  | Output :  "Autre"
Input  : améliorer le transfert des photos qui est lent et qui ne prend pas certains formats Input  : L'espace pour envoyer des documents en ligne est beaucoup trop restreint !  On ne peut pas envoyer grand chose...  Input  : Très compliqué d'envoyer un document de devis, une simple lettre de devis trop lourde pour être prise en charge. Obligé de refaire 3 fois l'envoi et donner des explications par courrier.  | Output :  "Autre"
Input  : J'ai mis plus de 5 minutes avant de trouver comment envoyer le document. Le site n'est pas du tout clair il faut vraiment chercher partout c'est une perte de temps  | Output :  "Autre"
Input  : DIFFICILE DE TRANSMETTRE DES DOCUMENTS ET LES PHOTOS . CAPACITE OU FORMAT REDUITS .  | Output :  "Autre"
Input  : Difficulté à transmettre de nombreuses photos  | Output :  "Autre"
Input  : souvent des problemes de transmission de documents  | Output :  "Autre"
Input  : il a fallut m'y reprendre 4 fois pour envoyer le document beug du site ? sinon ca allait  | Output :  "Autre"
Input  : Mais la messagerie et la transmission de documents via l'espace client sont défaillants  si bien que j'ai du adresser ordonnance médicale  facture de pharmacie et courriel explicatif a Groupama sous forme de mail  courant accompagné de piéces numérisées  | Output :  "Autre"
Input  : Manque dossier document déjà envoyé et en cours d'analyse  | Output :  "Autre"
Input  : Sauf erreur de ma part, il n'y a pas de rubrique permettant de retrouver les demandes de remboursements ou les envois de documents à Groupama. Pourtant, cela avait été soulevé lors de l'Assemblée Générale. Où en est-on de l'évolution du site incluant ces possibilités ?  | Output :  "Autre"
Input  : Lorsque j'envoie des documents, par exemple pour la santé ou pour d'autres raison, on a pas l'historique des documents envoyés, c'est très très très dérangeant, j'ai fait un paiement, je ne vois pas le paiement dans un quelconque historique, très dérangeant également  | Output :  "Autre"
Input  : Pas de possibilité de visualiser les documents transmis par nos soins avec la date de transmission  | Output :  "Autre"
Input  : impossible de retrouver les demandes qui ont été faites ou les documents qui ont été transmis  | Output :  "Autre"
Input  : Difficile de retrouver les documents envoyés  | Output :  "Autre"
Input  : document envoyé non retrouvé malgré accusé de réception que j'avais reçu obligé de le renvoyer  | Output :  "Autre"
Input  : On ne voit pas si les documents transmis sont effectivement au dossier.  | Output :  "Autre"
Input  : SITE INCOMPLET POUR EXEMPLE ON NE TROUVE PAS TRACE DES DOCUMENTS ENVOYES PAS NOS SOINS SUR LE SITE  | Output :  "Autre"
Input  : Le site était en panne ce matin et c'est régulier. | Output :  "Autre"
Input  : bugs permanents  | Output :  "Autre"
Input  : peu convivial  avec souvent des 'bugs'  | Output :  "Autre"
Input  : mauvaise gestion de votre site, il est en bug permanent  | Output :  "Autre"
Input  : bug sans cesse  | Output :  "Autre"
Input  : désolé mais toutes les pages indisponible pour le moment  | Output :  "Autre"
Input  : LE SITE NE FONCTIONNE PAS; 2 NAVIGATEURS DIFFÉRENTS  | Output :  "Autre"
Input  : L'application est horrible , bug sur bug tout est a revoir  | Output :  "Autre"
Input  : il bug assez souvent  | Output :  "Autre"
Input  : Rien ne fonctionne . Messages d'erreur| Output :  "Autre"
Input  : difficultés d'accès aux documents trop récurrentes : message d'erreur  | Output :  "Autre"
Input  : toujour en erreur  | Output :  "Autre"
Input  : extrêmement long pour au final avoir une erreur. Lamentable!  | Output :  "Autre"
Input  : connection à l'espace personnel extrememnt long, sans compter qu'a chaque connexion apparait invariablement un message d'erreur ! pour ensuite faire enfin apparaitre les infos demandées.D'autre part  les notifications restent en permanence sans jamais etre datées.Merci de veiller à la mise à jour de votre application.  | Output :  "Autre"
Input  : très mauvais connexion ....la page saute et apparait : Une erreur est survenue ...  | Output :  "Autre"
Input  : Page qui se charge et affiche erreur partout, je ne peux accéder à rien  | Output :  "Autre"
Input  : Beaucoup trop de messages d'erreurs et d'indisponibilités. Ergonomie à revoir.  | Output :  "Autre"
Input  : Il serait souhaitable, plutôt que de tchater avec le conseiller virtuel qui ne peut répondre à la question posée, de pouvoir échanger par le biais d'une messagerie| Output :  "Autre"
Input  : Un espace communication serait bienvenu afin d'échanger des mails; je souhaiterais l'envoi de mon attestation d'assurance de responsabilité civile 2024...  | Output :  "Autre"
Input  : Pas d'accès simple à une messagerie - Pas d'accès a la carte de mutuelle - Pas de suivi et historique des messages  | Output :  "Autre"
Input  : nous n'avons pas accès aux messages envoyés  pas de réponse depuis plus d'un mois pas de suivi des remboursements en temps réel  | Output :  "Autre"
Input  : Je n'ai pas trouvé d'espace messagerie avec conseiller  | Output :  "Autre"
Input  : le bouton 'messageries / courriers' n'est pas présent sur la page d'accueil. | Output :  "Autre"
Input  : Manque beaucoup de chose, ça manque déjà d'une messagerie pour demander quelque chose, sachant que le chat est un peu buggé.  | Output :  "Autre"
Input  : pas d'accès à espace échange courrier, le dialogue avec une IA ne me convient pas, je ne retrouve pas l'historique de mes échanges avec vous  | Output :  "Autre"
Input  : pas de possibilités de consulter l'historique des mails  | Output :  "Autre"
Input  : manque la messagerie  ?  | Output :  "Autre"
Input  : A chaque fois que je me connecte sur mon espace il y a noté que j'ai des notifications mais elles ne concernent pas les mails reçus dans ma boite mail. Ce sont toujours les mêmes et inutiles :'mes coordonnées, ayez le bon réflexes et alerte tempête' ces notifications devraient au contraire être en lien avec les mails que l'on reçoit car on doit justement chercher les infos reçues dans nos mails que les rubriques ce n'est vraiment pas pratiques et pas clairs. Alors que si les notifications seraient en lien avec ce que l'on reçoit par mail cela serait un gain de temps.  | Output: 'Problème de notifications'| Output :  "Autre"
Input  : comment faire pour enlever les notifications une fois lues. elles reviennent systématiquement. merci  | Output :  "Autre"
Input  : Site pas intuitif, affiche des notifications à chaque ouverture, un espace document envoyé qui ne fonctionne pas !  | Output :  "Autre"
Input  : Ce serait bien de ne pas toujours avoir les mêmes notifications (la cloche verte avec les numéros en rouge) qui réapparaissent à chaque fois même quand on les a déjà vus.  | Output :  "Autre"
Input  : Certaines notifications reviennent sans arrêt alors que je n'en ai pas besoin ; certificat assurance scolaire, changement de situation  | Output :  "Autre"
Input  : il y  a toujours une cloche et je ne reçois pas de notification lors d un changement dans mon dossier  | Output :  "Autre"
Input  : Dans 'notifications' toujours les mêmes messages ?  | Output :  "Autre"
Input  : Pouvez-vous trouver une solution pour lorsqu'on a lu les notifications celle-ci n'apparaissent plus car ça fait plus d'un an que les mêmes notifications me sont proposés chaque fois que je me rends sur ma page  | Output :  "Autre"
Input  : Les notifications sont infernales : on peut les supprimer, elles réapparaissent à la visite suivante. Et elles ne concernent en plus même pas des choses très importantes, comme un remboursement en attente ou que sais-je?  | Output :  "Autre"
Input  : LES NOTIFICATIONS INUTILES  | Output :  "Autre"
Input  : Identification compliquée Input  : difficulté à me connecter  | Output :  "Autre"
Input  : quelquefois, malgré un identifiant et un mot de passe correct, il est impossible d'accéder au site  | Output :  "Autre"
Input  : Trop difficile d'entrer les chiffres du 'mot de passe'  | Output :  "Autre"
Input  : Le mode d'authentification à base de chiffres seulement n'est pas pratique pour moi et même frustrant. Come indice : à chaque fois que je dois me connecter à votre site, soit une à deux fois par ans, je dois remettre mon mode de code secret, parce que je ne m'en souviens pas.   | Output :  "Autre"
Input  : Problème pour faire le mot de passe (lorsqu'on clique sur 1 chiffre, il y a un double-clic sur ce chiffre)  | Output :  "Autre"
Input  : je crois qu'il n'y a pas d'application plus nulle!inutilisable! ex:renseigner so N° de de tel,après le 33 impossible d'entrer le chiffres; a utre ex.on vous envoie un mot de passe ...rien;lorsqu'on a tapé son adresse mail 10 fois pour rien on décroche,conclusion:je n'ai pas d'espace client Groupama et je ne connaîtrais pas mes échéances  | Output :  "Autre"
Input  : Pourquoi un identifiant internet ????  | Output :  "Autre"
Input  : PETITE DIFFICULTE POUR REINITIALISER LE MOT DE PASSE.  | Output :  "Autre"
Input  : Toujours très mécontent du système d'authentification. Le pavé numérique empêche l'utilisation d'un gestionnaire de mot de passe, et je doute que ce soit conforme aux bonnes pratiques en terme d'accessibilité. Enfin, vous ne supportez pas d'authentification à double-facteur.  | Output :  "Autre"
Input  : toujours des difficultés pour accéder aux remboursements santé du conjoint , voir impossible. Améliorations nécessaires Input  : les remboursements du conjoint devrait apparaitrent puisque s'est le mem compte client???  comme il est impossible de creer un compte pour le conjoint ,celui-ci doit deviner  lors des remboursements que ce sont ses propre remboursements de soins???  | Output :  "Autre"
Input  : Comment trouver les remboursements du conjoint ?  | Output :  "Autre"
Input  : je voudrais pouvoir connecter mon conjoint avec son identifiant  | Output :  "Autre"
Input  : Les paiements de mon conjoint n'apparaisse pas dans mon espace santé  | Output :  "Autre"
Input  : Je ne vois que les remboursements de mon mari et rien me concernant  | Output :  "Autre"
Input  : je n'ai pas les remboursements pour mon mari, c'est le mÃªme contrat , j'aimerai un lien pour avoir accès son compte  | Output :  "Autre"
Input  : J'aimerai retrouver toutes mes informations sur mon espace personnel sans aller à chaque fois sur l'espace de mon mari!!!  | Output :  "Autre"
Input  : Je n arrive jamais à visualiser les remboursement s de mon mari laurent alain sinon pour le reste je mets la note de 9  | Output :  "Autre"
 Input  : pas facile de s'y retrouver| Output :  "Autre"
Input  : difficile de trouver les rubriques  | Output :  "Autre"
Input  : il faut cliquer partout pour chercher une information  | Output :  "Autre"
Input  : difficile de s y retrouver. rien ne correspond à mon besoin  | Output :  "Autre"
Input  : l'accès aux informations les plus importantes n'est pas très évidente  , la touche menu n'amène pas à grand chose  | Output :  "Autre"
Input  : pas très intuitif pour trouver l'info de suite, un peu trop de publicité dès le départ  | Output :  "Autre"
Input  : Pas facile de s'y retrouver  | Output :  "Autre"
Input  : Pas facile de comprendre la logique du site et donc de retrouver les documents recherchés.  | Output :  "Autre"
Input  : TROP CONFUS  | Output :  "Autre"
Input  : Consultation du site pas des plus intuitives (Pa évident de trouver comment mettre à jour les assolements de l'assurance récolte. Un lien depuis la page d'accueil serait bienvenu...)  | Output :  "Autre"
Input  : Dans le tchat, alors que je tapais mon numéro de téléphone j'avais comme réponse qu'il était invalide. Et je ne pouvais pas aller plus loin. | Output :  "Autre"
Input  : Impossible de joindre des documents pour compléter le sinistre, document que j ai déjà transmis puis a la demande d être rappelé et bien impossible de mettre mon numéro de téléphone car votre bot le reconnaît pas ....  | Output :  "Autre"
Input  : Votre conseiller virtuel est assez moyen et c'est bien dommage de ne pas pouvoir basculer sur un conseiller non virtuel en mesure de traiter les demandes  | Output :  "Autre"
Input  : conseiller virtuel a exclure  | Output :  "Autre"
Input  : Bonjour le robot répondeur n'accepte pas les réponses et pose toujours et inlassablement la même question .  | Output :  "Autre"
Input  : aide virtuelle est nulle, ne répond pas aux questions  | Output :  "Autre"
Input  : Le conssier virtuell aprés de longues minutes d'attente n'as pas rérondu a ma question  | Output :  "Autre"
Input  : La conversation Tchat avec le conseiller est inutile et sans réponse concret à part demander à l'employeur alors qu'il aurait pu me répondre  | Output :  "Autre"
Input  : le conseiller virtuel ne répond pas !  | Output :  "Autre"
Input  : La conversation virtuelle ne fonctionne pas et les devis auto non plus  | Output :  "Autre"
 Input  : pouvoir contacter directement son conseilller| Output :  "Autre"
Input  : je voulais envoyer un message à ma conseillère, je n'ai pas trouvé d'accès direct à sa boite mail.  | Output :  "Autre"
Input  : Peut-être pouvoir laisser un message directement au conseiller.  | Output :  "Autre"
Input  : impossible de contacter un conseillé pour un redez vous  | Output :  "Autre"
Input  : on ne peut pas contacter le service client par mail ou demander à être rappelé  | Output :  "Autre"
Input  : pas possible de joindre le conseiller  | Output :  "Autre"
Input  : Celà ne serait pas mal que je puisse contacter mon conseiller en accèdant à son e-mail dans mon espace client  | Output :  "Autre"
Input  : Je n'ai peut-être pas assez cherché, mais je n'ai pas trouvé le moyen d'adresser un mail facilement à ma conseillère sur le site.  | Output :  "Autre"
Input  : Je ne réussis pas toujours à obtenir les informations que je recherche, comme d'envoyer un e-mail à  mon conseiller par exemple.  | Output :  "Autre"
Input  : OÃ¹ peut on envoyer un mail Ã  Groupama? Sans passer par le conseiller virtuel qui ne rÃ©pond pas le week-end de toute faÃ§on.  | Output :  "Autre"
Input  : Améliorer la réactivité lors des transmission de documents| Output :  "Autre"
Input  : Depuis le 16 juin dossier toujours pas à jour et tout sa a cause de la faute d'un agent qui n'a pas fait son travail correctement. Vous m'envoyer a nouveau un document avec des erreurs et vous inscrivez « Votre contrat n'a pas pu être chargé dans sa totalité. Veuillez nous excuser pour la gêne occasionnée. ». C'est une honte de traiter les clients de cette façon. En plus sur le nouveau document vous m'avez supprimé les 50e offert pour ce nouveau contrat !!!| Output :  "Autre"
Input  : Bonjour, j'ai déclaré un sinistre à la date du 20/06/23.Un cabinet d'expertise est mandaté pour prendre rdv avec moi. Mail reçu le 3/7/23. de Groupama. Aucun retour du cabinet mandaté pour une prise de RDV. J'ai contacté le service sinistre à ce jour de Groupama qui trouve également cette situation pas normale et qui doit me faire un retour. J'ai également contacté le cabinet d'expertise qui à ce jour ne sont pas en mesure de me donner une date. Cd MATEUS Marco | Output :  "Autre"
Input  : je ne suis pas satisfaite ,j'ai demandé les détails de mon assurance dépendance et ce jour j'attends toujours la réponse  | Output :  "Autre"
Input  : plus de 20 ans que je suis client , je suis tres decu du service ou je doit relancer tout les 2 jours  | Output :  "Autre"
Input  : demande de devis dentaire déposé fin septembre 2023 toujours pas de réponse il faut toujours relancer  | Output :  "Autre"
Input  : répondre lorsque l'on envoit un message serait la moindre des choses  | Output :  "Autre"
Input  : aucune réponse à mes messages envoyés concernant des questions sur le remboursement d'un sinistre...  | Output :  "Autre"
Input  : Pas de réponse au demande  | Output :  "Autre"
Input  : J'ai fait il ya plusieurs jours une déclaration concernant mon habitation, à laquelle je n'ai pas reçu de réponse  | Output :  "Autre"
Input  : J attends une réponse  | Output :  "Autre"
Input  : Difficile d'avoir des réponses à mes questions, je suis toujours dans l'attente de l'avancée de mon contrat agrimut  | Output :  "Autre"
Input  : Je trouve que c'est long pour régler mon sinitre  | Output :  "Autre"
Input  : nom du medecin| Output :  "Autre"
Input  : manque de précision: par ex quand vous écrivez 'appareillage', j'ignore de quoi il s'agit ; dans certains cas vous mettez : 'remboursement à un tiers' qui est ce tiers ? ce n'est pas toujours indiqué ...s  | Output :  "Autre"
Input  : Le relevé des prestations santé n'est pas très clair. J'aimerais avoir plus d'infos sur l'identité des prestataires. Remboursement à un tiers ? Qui ?  | Output :  "Autre"
Input  : clarté dans le détail des remboursements santé  | Output :  "Autre"
Input  : manque de précisions sur les remboursements  | Output :  "Autre"
Input  : pour les remboursements les détails manque au premier regard ? remboursement de quoi ??  | Output :  "Autre"
Input  : Dans le détail des remboursements, ce serait bien de préciser lieu et nom du médecin remboursé!  | Output :  "Autre"
Input  : Comment vérifier les remboursements sans aucun détail a part la somme et la date du remboursement? Je ne vois pas de quelle prestation il s'agit, sa date? Quel soin ? Veuillez bien m'éclairer . Merci.  | Output :  "Autre"
Input  : Les remboursements ne sont pas clairs. Pas assez détaillé. Je n'arrive pas à trouver les factures que j'envoie  | Output :  "Autre"
Input  : pas assez de visibilité- nom du praticien pas indiqué - pas besoin du détail des honoraires - plus simple de regrouper tous les remboursements - En un mot, difficile de suivre ses remboursements et si vous indiquez les remboursements tiers payants, ce qui est justifié pour connaître les prestations de Groupama, soyez simple si non cela n'est pas efficace ni pédagogue  | Output :  "Autre"
Input  : je n'arrive pas à trouver mon échéancier 2024 | Output :  "Autre"
Input  : Difficile de trouver l'option  permettant de visualiser les nouvelles échéances  | Output :  "Autre"
Input  : Bonjour, Un nouvel avis d'échéance est disponible. Lorsque je veux le visualiser, cela m'indique que la page n'est pas disponible.  | Output :  "Autre"
Input  : La lecture des avis d'échéance n'est pas toujours très claire...  | Output :  "Autre"
Input  : Impossible trouver échéancier 2024  | Output :  "Autre"
Input  : Impossible de trouver le montant de mes échéances  | Output :  "Autre"
Input  : Votre site est compliqué : impossible de télécharger l'échéancier des cotisations 2024  | Output :  "Autre"
Input  : une catastrophe , ont ne retrouve rien !!!!! impossible de retrouver l echeancier   cest penible comparer a d autres societés  | Output :  "Autre"
Input  : demander en meme temps 2 attestations (habitation et auto plus) et l'echeancier global mensuel est difficile  | Output :  "Autre"
Input  : je  ne trouve  pas l echeancier 2022  | Output :  "Autre"
Je reçois un mail 'nouveau remboursement', j'y vais : ' aucun remboursement depuis 90 jours' !!! Hors sur mon compte bancaire j'en reçois !! | Output :  "Autre"
Input  : Le site est bien. Mais j'ai dû y surfer un peu avant de trouver le remboursement annoncé par un mail de Groupama  | Output :  "Autre"
Input  : je reçois un mail me parlant d'un nouveau document, mais sur le site aucune idée où se trouve se document  | Output :  "Autre"
Input  : lorsqu'on reçoit un mail nous informant d'un nouveau document disponible sur notre espace client, il faut chercher un peu partout. On pourrait s'attendre à avoir ces nouveaux documents en accès direct et non à chercher dans une liste.  | Output :  "Autre"
Input  : j'ai un courriel qui annonce un nouveau remboursement que je vois pas sur 'mes remboursements' | Output :  "Autre"
Input  : Je reçois ce jour un @mail m'indiquant que des informations sont disponobles dans mon espace client !!!  OU SONT CES INFORMATIONS ??? Dans un tel cas, il serait judicieux que ces 'choses' nouvelle soient clairement identifiées. Merci  | Output :  "Autre"
Input  : j'ai un nouveau document (parait-il) mais il est impossible d'ouvrir le dossier Relevé de prestation. et ce n'est ^pas la 1ere fois  | Output :  "Autre"
Input  : Un peu compliqué,  de plus on reçoit des notifications et quand on y rentre rien de spécial.  | Output :  "Autre"
Input  : je reçois notification d'un nouveau document consultable mais rien dans mon espace  | Output :  "Autre"
Input  : Mail reçu, mais lorsque je vais sur mon compte dans les notifications sont plus de la PUB que des signatures de contrat !!!!!  | Output :  "Autre"
Input  : Suivis de sinistres inexistants| Output :  "Autre"
Input  : je ne retrouve pas un sinistre declarer  | Output :  "Autre"
Input  : La visibilité sur les sinistres à améliorer, les notifications qui restent en rouge car un sinistre est ouvert à chaque connexion  | Output :  "Autre"
Input  : AUCUN SUIVI DE MES SINISTRES?  | Output :  "Autre"
Input  : quand un sinistre survient, le suivi n'est pas votre priorité!!!  | Output :  "Autre"
Input  : Aucune nouvelle de mon sinistre de mai 2022  | Output :  "Autre"
Input  : pour un sinistre il manque le suivi entre le gestionnaire et l'expert, ou le garage. / qu'on puisse retrouver les mêmes fonctionnalités sur l'appli mobile  | Output :  "Autre"
Input  : je ne sais pas si ma déclaration de sinistre est complète ou non . rien ne me le signal  | Output :  "Autre"
Input  : les mises à jour des sinistres semblent aléatoires aléatoires  | Output :  "Autre"
Input  : Mise en place d'un suivi par date des événements du sinistre (ex: missionnement expert, date d'expertise...)  | Output :  "Autre"
Input  : Pas toujours facile à voir les remboursements| Output :  "Autre"
Input  : difficile de voir nos remboursements santé  | Output :  "Autre"
Input  : Je n'ai plus accès à  mes remboursements santé,  et pas de solution depuis que j'ai appelé  vos services.  | Output :  "Autre"
Input  : Impossible d accéder à mes remboursements frais de sante  | Output :  "Autre"
Input  : impossible de trouver les remboursements de prestations de santé  | Output :  "Autre"
Input  : Impossible de trouver mes remboursements santé  | Output :  "Autre"
Input  : Sur l'espace de la SCEA du saule ainsi que sur celui des meubles GUILLOT , on n'a pas accès au détail des remboursements santé. On nous dit juste d'activer l'espace sans que l'on ait de mode d'emploi pour le faire. Il devrait juste y avoir un lien. Je suppose que c'est lié à des mesures de confidentialité mais c'est particulièrement rébarbatif. Dans ce cas , envoyez le détail  | Output :  "Autre"
Input  : Difficile d'accéder à mon compte remboursement  afin de voir mes remboursements et ma prise en charge  | Output :  "Autre"
Input  : mes remboursements ne sont pas présents en totalité et l'accrochage à la MGEN n'est pas fait depuis ma demande en mars 2021 !!!!  | Output :  "Autre"
Input  : Pas de visibilité sur le site pour les remboursements santé depuis plusieurs semaines.  | Output :  "Autre"
Input  : J essaye de télécharger mon attestation pour ma mutuelle impossible  à  faire| Output :  "Autre"
Input  : je n'arrive pas à accédé à ma carte d'assurance santé prévoyance  | Output :  "Autre"
Input  : ATTESTATION COMPLEMENTAIRE 2024  | Output :  "Autre"
Input  : Pas de carte de tiers-payant disponible (ni même sur l'application), le contrat avec les garanties est introuvable. En bref, du service tellement minimum que le site ne me sert pas.  | Output :  "Autre"
Input  : Faites un site qui fonctionne !!! impossible de recupérer sa carte de mutuelle !! la base quoi !  | Output :  "Autre"
Input  : impossible de trouver l'attestation tiers payant  | Output :  "Autre"
Input  : je ne peux pas avoir ma carte mutuelle probleme avec mon dossier  | Output :  "Autre"
Input  : Je met un car je ne peut rien faire Groupama est au courant je n'est mÃªme pas ma carte mutuelle donc je met 1 dÃ©soler  | Output :  "Autre"
Input  : impossible de trouver comment telecharger carte mutuelle devient compliquer  | Output :  "Autre"
Input  : possibilite de telecharge divers document style carte verte ou carte mutuelle  | Output :  "Autre"
Input  : Devis en ligne impossible | Output :  "Autre"
Input  : trop de probleme sur les devis et tarifs proposés  | Output :  "Autre"
Input  : difficulté pour réaliser un devis assurance auto  | Output :  "Autre"
Input  : on ne peu pas faire de devis pour une assurance remorque  | Output :  "Autre"
Input  : Impossible d'obtenir un devis  | Output :  "Autre"
Input  : Impossible de demander un simple devis auto en ligne... Etrange pour un client de plus de 40 ans à  qui votre application demande à  quel âge il aurait eu son permis !  | Output :  "Autre"
Input  : je venais pour un devis pour l'appartement de mon fils étudiant , et je n'ai pas eu la possibilitÃ© de la faire par pas d'option de ce type dans les choix proposés  | Output :  "Autre"
Input  : pas de devis en ligne  | Output :  "Autre"
Input  : pas possible de trouver un devis pour une moto, sur votre site vous avez que 3 modèles qui ne sont pas la mienne.  | Output :  "Autre"
Input  : devis 2 roues:  pas possible de trouver la marque donc impossible de continuer Ã  remplir le formulaire  | Output :  "Autre"
Input  : poiur effectuer un reglement,pas evident de trouver l'endrot......... | Output :  "Autre"
Input  : je voudrais regler mon assurance habitation et ne trouve pas comment faire  | Output :  "Autre"
Input  : J'essaie de trouver une manière pour payer l 'assurance auto sur l'espace client, mais je ne trouves rien.  | Output :  "Autre"
Input  : difficulté pour trouver le moyen de payer une cotisation  | Output :  "Autre"
Input  : Il serait plus pratique de pouvoir payer en ligne. Ou alors je n'ai vraiment pas trouvé comment procéder. Bien cordialement,  | Output :  "Autre"
Input  : Les documents ne sont pas à jour et on ne peut pas payer en ligne  | Output :  "Autre"
Input  : Je ne trouve pas la possibilité de payer ma cotisation en ligne.  | Output :  "Autre"
Input  : plus de possibilité de payer en ligne  | Output :  "Autre"
Input  : Je ne trouve pas l'endroit pour payer ma cotisation !  | Output :  "Autre"
Input  : il n'y a aucun onglet payer ses factures sur l'écran d'accueil, il faut passer par la messagerie  | Output :  "Autre"
Input  : IMPOSSIBLE DE TROUVER SON RELEVE D'INFORMATION | Output :  "Autre"
Input  : Il faudrait pouvoir télécharger le relevé d'information directement et non attendre qu'il soit envoyé par mail  | Output :  "Autre"
Input  : impossible d avoir un releve d information sur votre site  tres mal fait !!!!  | Output :  "Autre"
Input  : Pourquoi je n'ai pas accès à mon relevé d'informations auto directement sur mon espace personnel ?  | Output :  "Autre"
Input  : j'ai besoin d'un relevé d'informations auto,  où est-ce que je peux le trouver ?  | Output :  "Autre"
Input  : je ne peux pas voir les relevés de prestation faites après le 13 octobre alors que nous sommes mi décembre. Pourquoi ?| Output :  "Autre"
Input  : pas évident de retrouver les relevés de prestations santé  | Output :  "Autre"
Input  : Je n'ai plus dans mes documents le 'relevé de prestations assuré' !!!!  | Output :  "Autre"
Input  : Manque releve mensuel de tous remboursements  | Output :  "Autre"
Input  : Impossible de visualiser les relevés de prestations de plus de 10 mois _ rien en 'archives'  | Output :  "Autre"
Input  : je n'arrive pas à visualiser les relevés de prestations maladie. aucun erreur d'affichage  | Output :  "Autre"
Input  : Demande de relevé de prestations introuvable, cela ne s'ouvre pas sur la bonne page, site pas assez clair.   | Output :  "Autre"
Input  : ABSENCE RELEVE PRESTATION MALADIE DETAIL DES RELEVES INSUFFISANTS APPAREILLAGE TROP VAGUE ??  | Output :  "Autre"
Input  : QUAND IL Y A PLUSIEURS BENEFICIAIRES IL FAUT CHARGER LES RELEVES UN A UN ET LA ON VOIT  | Output :  "Autre"
Input  : jE N'AI PAS TROUVE  COMMENT ALLER SUR : RELEVE DE PRESTATIONS SANTE. A VOUS LIRE OU ...  | Output :  "Autre"
 Input  : pas d'option de résiliation / site peu clair| Output :  "Autre"
Input  : Bonjour je voudrais résilier le contrat Amont car bientôt j'aurais une petite retraite. Merci  | Output :  "Autre"
Input  : je n'arrive pas à trouver comment résilier un contrat auto suite à une vente... donc je suis très décu...  | Output :  "Autre"
Input  : IMPOSSIBLE DE RESILIER EN LIGNE DANS MON ESPACE CLINT  | Output :  "Autre"
Input  : site inutile vu que aucune résiliation possible, aucune réclamation parce que 'soucis techniques' récurrent foutage de tête du client  | Output :  "Autre"
Input  : Pas moyen de trouver ou resilier un contrat en ligne  | Output :  "Autre"
Input  : Je souhaitais résilier une assurance...  | Output :  "Autre"
Input  : Depuis le 01/06/2023, les clients ont la possibilité de résilier leur contrat en ligne. Sauf erreur de ma part, je ne trouve pas cette option sur votre site.  | Output :  "Autre"
Input  : pas de travail effectuer pour la mise en application de la résiliation en ligne  | Output :  "Autre"
Input  : impossible de trouver la rubrique résiliation.  | Output :  "Autre"
Input  : Les adresses de Parodontistes ne sont pas à jour sur le groupe Servane. Celui de Sautron est en retraite...| Output :  "Autre"
Input  : Liste de garages partenaires inexistante  | Output :  "Autre"
Input  : IMPOSSIBLE DE TROUVER UN GARAGE PARTENAIRE SUITE BRIS DE GLACE  | Output :  "Autre"
Input  : Il manque la liste des garages partenaires  | Output :  "Autre"
Input  : Impossible de visualiser de façon fluide les opticiens Sévéane sur une zone géographique. On dirait que vous ne voulez pas donner l'information. Pour Paris, il faut faire tous les arrondissements un par un. A quand une liste mise à jour par département ?  | Output :  "Autre"
Input  : Opticiens Sévéane non renseignés  | Output :  "Autre"
Input  : Pas d'information précise sur les partenaires sevean  | Output :  "Autre"
Input  : A la recherche d'un opticien Seveane, tous les opticiens faisant partie du réseau ne sont pas mentionnés dans la liste par arrondissement. Il a fallu que je recherche manuellement pour le trouver.  | Output :  "Autre"
Input  : je ne trouve pas le partenaire SEVEANE  | Output :  "Autre"
Input  : j'ai toujours beaucoup de mal à trouver où se trouve mes remboursements et comment trouver un partenaire Seveane  | Output :  "Autre"
 Input  : J'ai un document à signer je ne le trouve pas| Output :  "Autre"
Input  : bonjour.ne trouve pas les documents à signer merci  | Output :  "Autre"
Input  : On m'impose de signer un contrat par internet et il est introuvable!!!!!!  | Output :  "Autre"
Input  : Signer un document ne fonctionne pas  | Output :  "Autre"
Input  : peu conviviale exemple je ne trouve pas l'endroit ou je dois signer mes modif de contrat  | Output :  "Autre"
Input  : bug signature électronique  | Output :  "Autre"
Input  : je recois parfois des relances de signatures alors que tout est ok  | Output :  "Autre"
Input  : Impossible d'avoir une signature électronique des documents  | Output :  "Autre"
Input  : documents de signature de contrat difficiles d'accès (accessibles depuis le lien envoyé mais pas quand on est déjà  connecté à  l'espace cllient  | Output :  "Autre"
Input  : Je reçois un mail pour une signature électronique mais je ne le trouve pas quand je me connecte  | Output :  "Autre"
Input  : C'est génial de nous envoyer un mail pour nous informer d'un nouveau document| Output :  "Autre"
Input  : Clair, facile impeccable| Output :  "Autre"
Input  : Très satisfaite, documents clairs  | Output :  "Autre"
Input  : intuitif et rapide  | Output :  "Autre"
Input  : intuitif et rapide  | Output :  "Autre"
Input  : disponibilité, accueil téléphonique très agréable et soutenant, à l'écoute  | Output :  "Autre"
Input  : Le site est très bien fait et surtout c'est très clair. Les documents sont très bien visualisés.  | Output :  "Autre"
Input  : Dossier traité très rapidement pour cet accident,je remercie groupama et la personne chargée du dossier  | Output :  "Autre"
Input  : Bonjour     je suis très satisfait  de ma visite, tout est bien et j'ai trouvé le règlement de mon indemnité sinistre maison d' habitation, Merci à vous!  | Output :  "Autre"
Input  : bonne présentation de l'espace client groupama à maintenir merci  | Output :  "Autre"
Input  : D'usage vraiment tres facile puisque j'ai réussi du 1er coup alors que je suis complètement néophyte en informatique  | Output :  "Autre"
Input  : Conseillers de l'agence de Montguyon et Montendre désagréables, peu professionnels et peu compétents. | Output :  "Autre"
Input  : Toujours difficile quand on est âgé  | Output :  "Autre"
Input  : je regrette fortement les relations humaines | Output :  "Autre"
Input  : Par exemple impossible de modifier de  façon simple mes données bancaires | Output :  "Autre"
Input  : Je n'ai pas eu le temps de le visionner que vous me demandez mon avis ?!?!| Output :  "Autre"
Input  : J'attends le relevé de situation au 31/01/2022. Taux servi du fonds euro en 2021 ? | Output :  "Autre"
Input  : dommage que l'assurance vie ne soit pas à  jour et que le taux d'intérêt 2021 ne soit pas encore servi le 06 février | Output :  "Autre"
Input  : TOUT PASSE PAR INFORMATIQUE .... | Output :  "Autre"
Input  : Problèmes de saisie sur appli. Qare.fr  date de naissance impossible!  | Output :  "Autre"
Input  : Je n'ai pas réussi à  prendre mon rdv | Output :  "Autre"
Input  : Je n'ai pas pû assurer mon auto | Output :  "Autre"
Input  : impossible de completter ma declaration de sinistre habitation | Output :  "Autre"
Input  : pouvoir ajouter des documents une fois le sinistre déclaré (plainte par exemple)| Output :  "Autre"
Input: transfert des contrats sur région atlantique illisible. a priori aucune cloture sur nantes bretatagne | Output :  "Autre"
Input: je voulais déclarer un accident de la vie pour ma fille Marie en ligne, ce n'était pas possible, dommage.| Output :  "Autre"
Input: Je n'ai pas pû assurer mon véhicule| Output :  "Autre"
Input: Je regrette de n'avoir pas pu signaler mon changement de véhicule. | Output :  "Autre"
Input: très déçu puisque ma véranda n'est pas assurée, alors qu'elle existe depuis de nombreuses années. Donc pas assuré pour les dégâts de la grêle.| Output :  "Autre"
Input: pouvoir ajouter des documents une fois le sinistre déclaré (plainte par exemple) | Output :  "Autre"
Input: n'ayant jamais eu de sinistre, je pensais que ma franchise serais offerte, déception | Output :  "Autre"
Input  : Je n'ai pas pû assurer mon auto | Output:"Autre
Input  : impossible de completter ma declaration de sinistre habitation | Output :"Autre"
Input  : pouvoir ajouter des documents une fois le sinistre déclaré (plainte par exemple)" | Output  :"Autre"
Input: transfert des contrats sur région atlantique illisible. a priori aucune cloture sur nantes bretatagne | Output  :"Autre"
Input: je voulais déclarer un accident de la vie pour ma fille Marie en ligne, ce n'était pas possible, dommage. | Output  :"Autre
Input: Je n'ai pas pû assurer mon véhicule | Output:"Autre"
Input: Je regrette de n'avoir pas pu signaler mon changement de véhicule. | Output :"Autre"
Input: très déçu puisque ma véranda n'est pas assurée, alors qu'elle existe depuis de nombreuses années. Donc pas assuré pour les dégâts de la grêle. | Output :"Autre"
Input: pouvoir ajouter des documents une fois le sinistre déclaré (plainte par exemple) | Output   :"Autre"
Input: n'ayant jamais eu de sinistre, je pensais que ma franchise serais offerte, déception | Output   :"Autre"




FIN EXEMPLES
"""

# - Verbatim_Indechiffrable: Cette classe doit être utilisée lorsque l’internaute dépose un Verbatim vide de sens, illisible, incompréhensible, cela peut être des lettres ou des  chiffres etc Exemple : h . Exemple : 455.
